DROP TABLE POST_ATTACHMENT;
DROP TABLE POST;
DROP TABLE BLOG;


CREATE TABLE BLOG(
  blog_id number primary key,
  title varchar2(256),
  owner varchar2(50 BYTE) ,
  description varchar2(1024),
  image	BLOB,
  reg_date	DATE default sysdate,
  update_date	DATE default sysdate
);

CREATE SEQUENCE BLOG_SEQ;

CREATE TABLE POST(
  POST_ID	NUMBER PRIMARY KEY,
  BLOG_ID 	NUMBER REFERENCES BLOG(BLOG_ID),
  TITLE		VARCHAR2(256 BYTE),
  READ_CNT	NUMBER default 0,
  CONTENT	CLOB,
  REG_DATE	DATE default sysdate,
  UPDATE_DATE	DATE default sysdate
);

CREATE SEQUENCE POST_SEQ;

CREATE TABLE POST_ATTACHMENT(
  ATTACHMENT_ID NUMBER PRIMARY KEY,
  POST_ID NUMBER REFERENCES POST(POST_ID),
  ORIGINAL_NAME	VARCHAR2(128 CHAR),
  FILE_SIZE	NUMBER,
  REG_DATE	DATE default sysdate
);

CREATE SEQUENCE POST_ATTACH_SEQ;

CREATE TABLE BOARD_ATTACHMENT(
  ATTACHMENT_ID NUMBER PRIMARY KEY,
  BOARD_ID NUMBER REFERENCES BOARD(BOARD_ID),
  ORIGINAL_NAME	VARCHAR2(128 CHAR),
  FILE_SIZE	NUMBER,
  REG_DATE	DATE default sysdate
);

CREATE SEQUENCE BOARD_ATTACH_SEQ;


select * from blog;
