CREATE TABLE REPLY(
	REPLY_ID 		NUMBER PRIMARY KEY,
 	GROUP_ID		NUMBER,			-- 연관 게시글 번호
 	TABLE_NAME		VARCHAR2(20),
	PARENT			NUMBER, 			-- 상위 댓글 번호
	WRITER			VARCHAR2(20) NOT NULL,
	PASSWORD 		VARCHAR2(20) NOT NULL,
	CONTENT			VARCHAR2(1024),
	DELETED			NUMBER(1) DEFAULT(0),	-- 삭제 여부, 실제 삭제하지 않음
	REG_DATE		DATE DEFAULT(SYSDATE),
	UPDATE_DATE	DATE DEFAULT(SYSDATE)
);
CREATE SEQUENCE REPLY_SEQ;
commit;
